### ISSUE TITLE
Errors in Tripal3 installation

### ISSUE THREAD

**Issue by alslonik** [tripal/tripal#1415]
# BUG/ERROR report
Hi, we are trying to install Tripal with no success. Here are the details. 
### Tripal Version: 3
* Drupal Version: 7
* PostgreSQL Version: 14
* PHP Version: 8.1

### Issue description
We have installation errors and are not able to install tripal, although we follow the steps as in documentation
https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/rapid_install.html

#### Error messages and screenshots
Now installing Drupal.

--2023-02-07 14:34:59--  https://www.drupal.org/files/projects/drupal-7.78.tar.gz
Resolving www.drupal.org (www.drupal.org)... 151.101.2.217, 151.101.66.217, 151.101.130.217, ...
Connecting to www.drupal.org (www.drupal.org)|151.101.2.217|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3335651 (3.2M) [application/x-gzip]
Saving to: ‘drupal-7.78.tar.gz.3’

     0K .......... .......... .......... .......... ..........  1%  662K 5s
    50K .......... .......... .......... .......... ..........  3% 1005K 4s
   100K .......... .......... .......... .......... ..........  4% 3.33M 3s
   150K .......... .......... .......... .......... ..........  6% 4.18M 2s
   200K .......... .......... .......... .......... ..........  7% 1.50M 2s
   250K .......... .......... .......... .......... ..........  9% 5.41M 2s
   300K .......... .......... .......... .......... .......... 10% 6.27M 2s
   350K .......... .......... .......... .......... .......... 12% 6.98M 1s
   400K .......... .......... .......... .......... .......... 13% 7.75M 1s
   450K .......... .......... .......... .......... .......... 15% 9.06M 1s
   500K .......... .......... .......... .......... .......... 16% 1.81M 1s
   550K .......... .......... .......... .......... .......... 18% 10.6M 1s
   600K .......... .......... .......... .......... .......... 19% 10.1M 1s
   650K .......... .......... .......... .......... .......... 21% 14.3M 1s
   700K .......... .......... .......... .......... .......... 23% 12.8M 1s
   750K .......... .......... .......... .......... .......... 24% 13.7M 1s
   800K .......... .......... .......... .......... .......... 26% 14.8M 1s
   850K .......... .......... .......... .......... .......... 27% 17.1M 1s
   900K .......... .......... .......... .......... .......... 29% 12.1M 1s
   950K .......... .......... .......... .......... .......... 30% 15.4M 1s
  1000K .......... .......... .......... .......... .......... 32% 19.8M 1s
  1050K .......... .......... .......... .......... .......... 33% 2.19M 1s
  1100K .......... .......... .......... .......... .......... 35% 20.1M 1s
  1150K .......... .......... .......... .......... .......... 36% 19.9M 1s
  1200K .......... .......... .......... .......... .......... 38% 21.7M 1s
  1250K .......... .......... .......... .......... .......... 39% 21.8M 0s
  1300K .......... .......... .......... .......... .......... 41% 26.6M 0s
  1350K .......... .......... .......... .......... .......... 42% 21.3M 0s
  1400K .......... .......... .......... .......... .......... 44% 16.5M 0s
  1450K .......... .......... .......... .......... .......... 46% 31.6M 0s
  1500K .......... .......... .......... .......... .......... 47% 21.2M 0s
  1550K .......... .......... .......... .......... .......... 49% 33.0M 0s
  1600K .......... .......... .......... .......... .......... 50% 37.4M 0s
  1650K .......... .......... .......... .......... .......... 52% 21.5M 0s
  1700K .......... .......... .......... .......... .......... 53% 41.0M 0s
  1750K .......... .......... .......... .......... .......... 55% 22.8M 0s
  1800K .......... .......... .......... .......... .......... 56% 26.9M 0s
  1850K .......... .......... .......... .......... .......... 58% 40.6M 0s
  1900K .......... .......... .......... .......... .......... 59% 31.8M 0s
  1950K .......... .......... .......... .......... .......... 61% 28.5M 0s
  2000K .......... .......... .......... .......... .......... 62% 39.4M 0s
  2050K .......... .......... .......... .......... .......... 64% 43.6M 0s
  2100K .......... .......... .......... .......... .......... 66% 26.7M 0s
  2150K .......... .......... .......... .......... .......... 67% 2.44M 0s
  2200K .......... .......... .......... .......... .......... 69% 20.7M 0s
  2250K .......... .......... .......... .......... .......... 70% 55.7M 0s
  2300K .......... .......... .......... .......... .......... 72% 38.1M 0s
  2350K .......... .......... .......... .......... .......... 73% 42.2M 0s
  2400K .......... .......... .......... .......... .......... 75% 30.8M 0s
  2450K .......... .......... .......... .......... .......... 76% 48.8M 0s
  2500K .......... .......... .......... .......... .......... 78% 56.5M 0s
  2550K .......... .......... .......... .......... .......... 79% 39.0M 0s
  2600K .......... .......... .......... .......... .......... 81% 40.5M 0s
  2650K .......... .......... .......... .......... .......... 82% 55.7M 0s
  2700K .......... .......... .......... .......... .......... 84% 34.8M 0s
  2750K .......... .......... .......... .......... .......... 85% 62.9M 0s
  2800K .......... .......... .......... .......... .......... 87% 47.2M 0s
  2850K .......... .......... .......... .......... .......... 89% 64.4M 0s
  2900K .......... .......... .......... .......... .......... 90% 34.6M 0s
  2950K .......... .......... .......... .......... .......... 92% 46.0M 0s
  3000K .......... .......... .......... .......... .......... 93% 39.5M 0s
  3050K .......... .......... .......... .......... .......... 95% 55.6M 0s
  3100K .......... .......... .......... .......... .......... 96% 42.5M 0s
  3150K .......... .......... .......... .......... .......... 98% 99.9M 0s
  3200K .......... .......... .......... .......... .......... 99% 53.3M 0s
  3250K .......                                               100%  111M=0.4s

2023-02-07 14:35:00 (8.20 MB/s) - ‘drupal-7.78.tar.gz.3’ saved [3335651/3335651]

mv: cannot move 'drupal-7.78/includes' to './includes': Directory not empty
mv: cannot move 'drupal-7.78/misc' to './misc': Directory not empty
mv: cannot move 'drupal-7.78/modules' to './modules': Directory not empty
mv: cannot move 'drupal-7.78/profiles' to './profiles': Directory not empty
mv: cannot move 'drupal-7.78/scripts' to './scripts': Directory not empty
mv: cannot move 'drupal-7.78/sites' to './sites': Directory not empty
mv: cannot move 'drupal-7.78/themes' to './themes': Directory not empty
You are about to DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                                                            [ok]
PHP Fatal error:  During inheritance of PDO: Uncaught ArgumentCountError: Too few arguments to function _drupal_error_handler(), 4 passed in /home/ron/Public/includes/install.inc on line 261 and exactly 5 expected in /home/ron/Public/includes/bootstrap.inc:2603
Stack trace:
#0 /home/ron/Public/includes/install.inc(261): _drupal_error_handler()
#1 /home/ron/Public/includes/install.inc(261): require_once()
#2 /home/ron/Public/includes/install.inc(238): drupal_get_database_types()
#3 /home/ron/Public/modules/system/system.install(159): drupal_detect_database_types()
#4 /home/ron/Public/includes/install.inc(1189): system_requirements()
#5 /home/ron/Public/includes/install.core.inc(1632): drupal_check_profile()
#6 /home/ron/Public/includes/install.core.inc(743): install_check_requirements()
#7 /home/ron/Public/includes/install.core.inc(471): install_verify_requirements()
#8 /home/ron/Public/includes/install.core.inc(339): install_run_task()
#9 /home/ron/Public/includes/install.core.inc(77): install_run_tasks()
#10 phar:///usr/local/bin/drush/includes/drush.inc(727): install_drupal()
#11 phar:///usr/local/bin/drush/includes/drush.inc(713): drush_call_user_func_array()
#12 phar:///usr/local/bin/drush/commands/core/drupal/site_install_7.inc(86): drush_op()
#13 phar:///usr/local/bin/drush/commands/core/site_install.drush.inc(275): drush_core_site_install_version()
#14 phar:///usr/local/bin/drush/includes/command.inc(422): drush_core_site_install()
#15 phar:///usr/local/bin/drush/includes/command.inc(231): _drush_invoke_hooks()
#16 phar:///usr/local/bin/drush/includes/command.inc(199): drush_command()
#17 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch()
#18 phar:///usr/local/bin/drush/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#19 phar:///usr/local/bin/drush/includes/startup.inc(465): drush_main()
#20 phar:///usr/local/bin/drush/includes/startup.inc(369): drush_run_main()
#21 phar:///usr/local/bin/drush/drush(114): drush_startup()
#22 /usr/local/bin/drush(14): require('...')
#23 {main} in /home/ron/Public/includes/database/database.inc on line 187
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                       [error]
Error: During inheritance of PDO: Uncaught ArgumentCountError: Too few arguments to function _drupal_error_handler(), 4 passed in /home/ron/Public/includes/install.inc on line 261 and exactly 5
expected in /home/ron/Public/includes/bootstrap.inc:2603
Stack trace:
#0 /home/ron/Public/includes/install.inc(261): _drupal_error_handler()
#1 /home/ron/Public/includes/install.inc(261): require_once()
#2 /home/ron/Public/includes/install.inc(238): drupal_get_database_types()
#3 /home/ron/Public/modules/system/system.install(159): drupal_detect_database_types()
#4 /home/ron/Public/includes/install.inc(1189): system_requirements()
#5 /home/ron/Public/includes/install.core.inc(1632): drupal_check_profile()
#6 /home/ron/Public/includes/install.core.inc(743): install_check_requirements()
#7 /home/ron/Public/includes/install.core.inc(471): install_verify_requirements()
#8 /home/ron/Public/includes/install.core.inc(339): install_run_task()
#9 /home/ron/Public/includes/install.core.inc(77): install_run_tasks()
#10 phar:///usr/local/bin/drush/includes/drush.inc(727): install_drupal()
#11 phar:///usr/local/bin/drush/includes/drush.inc(713): drush_call_user_func_array()
#12 phar:///usr/local/bin/drush/commands/core/drupal/site_install_7.inc(86): drush_op()
#13 phar:///usr/local/bin/drush/commands/core/site_install.drush.inc(275): drush_core_site_install_version()
#14 phar:///usr/local/bin/drush/includes/command.inc(422): drush_core_site_install()
#15 phar:///usr/local/bin/drush/includes/command.inc(231): _drush_invoke_hooks()
#16 phar:///usr/local/bin/drush/includes/command.inc(199): drush_command()
#17 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch()
#18 phar:///usr/local/bin/drush/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#19 phar:///usr/local/bin/drush/includes/startup.inc(465): drush_main()
#20 phar:///usr/local/bin/drush/includes/startup.inc(369): drush_run_main()
#21 phar:///usr/local/bin/drush/drush(114): drush_startup()
#22 /usr/local/bin/drush(14): require('...')
#23 {main} in /home/ron/Public/includes/database/database.inc, line 187

Downloading modules.
Install location /home/ron/Public/sites/all/modules/field_group already exists. Do you want to overwrite it? (y/n): y
Project field_group (7.x-1.8) downloaded to /home/ron/Public/sites/all/modules/field_group.                                                                                                              [success]
Install location /home/ron/Public/sites/all/modules/field_group_table already exists. Do you want to overwrite it? (y/n): y
Project field_group_table (7.x-1.7) downloaded to /home/ron/Public/sites/all/modules/field_group_table.                                                                                                  [success]
Install location /home/ron/Public/sites/all/modules/field_formatter_class already exists. Do you want to overwrite it? (y/n): y
Project field_formatter_class (7.x-1.2) downloaded to /home/ron/Public/sites/all/modules/field_formatter_class.                                                                                          [success]
Install location /home/ron/Public/sites/all/modules/field_formatter_settings already exists. Do you want to overwrite it? (y/n): y
Project field_formatter_settings (7.x-1.1) downloaded to /home/ron/Public/sites/all/modules/field_formatter_settings.                                                                                    [success]
Install location /home/ron/Public/sites/all/modules/ctools already exists. Do you want to overwrite it? (y/n): y
Project ctools (7.x-1.21) downloaded to /home/ron/Public/sites/all/modules/ctools.                                                                                                                       [success]
Project ctools contains 10 modules: views_content, ctools_access_ruleset, page_manager, bulk_export, ctools_custom_content, stylizer, ctools_plugin_example, term_depth, ctools_ajax_sample, ctools.
Install location /home/ron/Public/sites/all/modules/date already exists. Do you want to overwrite it? (y/n): y
Project date (7.x-2.14) downloaded to /home/ron/Public/sites/all/modules/date.                                                                                                                           [success]
Project date contains 10 modules: date_migrate, date_all_day, date_tools, date_views, date_popup, date_repeat, date_context, date_repeat_field, date_api, date.
Install location /home/ron/Public/sites/all/modules/devel already exists. Do you want to overwrite it? (y/n): y
Project devel (7.x-1.7) downloaded to /home/ron/Public/sites/all/modules/devel.                                                                                                                          [success]
Project devel contains 3 modules: devel_generate, devel, devel_node_access.
Install location /home/ron/Public/sites/all/modules/ds already exists. Do you want to overwrite it? (y/n): y
Project ds (7.x-2.16) downloaded to /home/ron/Public/sites/all/modules/ds.                                                                                                                               [success]
Project ds contains 7 modules: ds_search, ds_format, ds_ui, ds_extras, ds_forms, ds_devel, ds.
Install location /home/ron/Public/sites/all/modules/link already exists. Do you want to overwrite it? (y/n): y
Project link (7.x-1.11) downloaded to /home/ron/Public/sites/all/modules/link.                                                                                                                           [success]
Install location /home/ron/Public/sites/all/modules/entity already exists. Do you want to overwrite it? (y/n): y
Project entity (7.x-1.10) downloaded to /home/ron/Public/sites/all/modules/entity.                                                                                                                       [success]
Project entity contains 2 modules: entity_token, entity.
Install location /home/ron/Public/sites/all/modules/libraries already exists. Do you want to overwrite it? (y/n): y
Project libraries (7.x-2.5) downloaded to /home/ron/Public/sites/all/modules/libraries.                                                                                                                  [success]
Install location /home/ron/Public/sites/all/modules/redirect already exists. Do you want to overwrite it? (y/n): y
Project redirect (7.x-1.0-rc4) downloaded to /home/ron/Public/sites/all/modules/redirect.                                                                                                                [success]
Install location /home/ron/Public/sites/all/modules/token already exists. Do you want to overwrite it? (y/n): y
Project token (7.x-1.9) downloaded to /home/ron/Public/sites/all/modules/token.                                                                                                                          [success]
Install location /home/ron/Public/sites/all/modules/tripal already exists. Do you want to overwrite it? (y/n): y
Project tripal (7.x-3.4) downloaded to /home/ron/Public/sites/all/modules/tripal.                                                                                                                        [success]
Project tripal contains 24 modules: tripal_ds, tripal_chado, tripal_analysis, tripal_cv, tripal_genetic, tripal_pub, tripal_phylogeny, tripal_featuremap, tripal_feature, tripal_library, tripal_stock, tripal_natural_diversity, tripal_contact, tripal_views, tripal_db, tripal_core, tripal_phenotype, tripal_organism, tripal_project, tripal_daemon, tripal_ws, tripal_chado_views, tripal, tripal_bulk_loader.
Install location /home/ron/Public/sites/all/modules/uuid already exists. Do you want to overwrite it? (y/n): y
Project uuid (7.x-1.3) downloaded to /home/ron/Public/sites/all/modules/uuid.                                                                                                                            [success]
Project uuid contains 4 modules: uuid_services_example, uuid_services, uuid_path, uuid.
Install location /home/ron/Public/sites/all/modules/jquery_update already exists. Do you want to overwrite it? (y/n): y
Project jquery_update (7.x-4.1) downloaded to /home/ron/Public/sites/all/modules/jquery_update.                                                                                                          [success]
Install location /home/ron/Public/sites/all/modules/views already exists. Do you want to overwrite it? (y/n): y
Project views (7.x-3.28) downloaded to /home/ron/Public/sites/all/modules/views.                                                                                                                         [success]
Project views contains 2 modules: views, views_ui.
Install location /home/ron/Public/sites/all/modules/webform already exists. Do you want to overwrite it? (y/n): y
Project webform (7.x-4.25) downloaded to /home/ron/Public/sites/all/modules/webform.                                                                                                                     [success]

Enabling modules.
Command pm-enable needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.                                                   [error]
The drush command 'en ctools date devel ds link entity libraries redirect token uuid jquery_update views webform field_group field_group_table field_formatter_class field_formatter_settings views_ui'  [error]
could not be executed.
Drush was not able to start (bootstrap) the Drupal database.                                                                                                                                             [error]
Hint: This may occur when Drush is trying to:
 * bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the URI to use with the
--uri parameter on the command line. See `drush topic docs-aliases` for details.
 * connect the database through a socket. The socket file may be wrong or the php-cli may have no access to it in a jailed shell. See http://drupal.org/node/1428638 for details.
 * connect to the database through a cli command using the --defaults-extra-file parameter to pass credentials through a tmp file. This method can break if other credentials are specified in a
~/.my.cnf file in your home directory. You may have to delete or rename the ~/.my.cnf file in your home directory.

Drush was attempting to connect to: 
 Drupal version         :  7.78                       
 Site URI               :  http://default             
 PHP configuration      :  /etc/php/8.1/cli/php.ini   
 PHP OS                 :  Linux                      
 Drush script           :  /usr/local/bin/drush       
 Drush version          :  8.4.11                     
 Drush temp directory   :  /tmp                       
 Drush configuration    :                             
 Drush alias files      :                             
 Drupal root            :  /home/ron/Public           
 Drupal Settings File   :  sites/default/settings.php 
 Site path              :  sites/default              

Applying patches.
--2023-02-07 14:35:23--  https://drupal.org/files/drupal.pgsql-bytea.27.patch
Resolving drupal.org (drupal.org)... 151.101.66.217, 151.101.130.217, 151.101.2.217, ...
Connecting to drupal.org (drupal.org)|151.101.66.217|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.drupal.org/files/drupal.pgsql-bytea.27.patch [following]
--2023-02-07 14:35:24--  https://www.drupal.org/files/drupal.pgsql-bytea.27.patch
Resolving www.drupal.org (www.drupal.org)... 151.101.130.217, 151.101.194.217, 151.101.66.217, ...
Connecting to www.drupal.org (www.drupal.org)|151.101.130.217|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1613 (1.6K) [text/plain]
Saving to: ‘drupal.pgsql-bytea.27.patch.3’

     0K .                                                     100% 24.0M=0s

2023-02-07 14:35:24 (24.0 MB/s) - ‘drupal.pgsql-bytea.27.patch.3’ saved [1613/1613]

Enabling Tripal modules.
Command pm-enable needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.                                                   [error]
The drush command 'en tripal tripal_chado tripal_ds tripal_ws' could not be executed.                                                                                                                    [error]
Drush was not able to start (bootstrap) the Drupal database.                                                                                                                                             [error]
Hint: This may occur when Drush is trying to:
 * bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the URI to use with the
--uri parameter on the command line. See `drush topic docs-aliases` for details.
 * connect the database through a socket. The socket file may be wrong or the php-cli may have no access to it in a jailed shell. See http://drupal.org/node/1428638 for details.
 * connect to the database through a cli command using the --defaults-extra-file parameter to pass credentials through a tmp file. This method can break if other credentials are specified in a
~/.my.cnf file in your home directory. You may have to delete or rename the ~/.my.cnf file in your home directory.

Drush was attempting to connect to: 
 Drupal version         :  7.78                       
 Site URI               :  http://default             
 PHP configuration      :  /etc/php/8.1/cli/php.ini   
 PHP OS                 :  Linux                      
 Drush script           :  /usr/local/bin/drush       
 Drush version          :  8.4.11                     
 Drush temp directory   :  /tmp                       
 Drush configuration    :                             
 Drush alias files      :                             
 Drupal root            :  /home/ron/Public           
 Drupal Settings File   :  sites/default/settings.php 
 Site path              :  sites/default              

Clear cache.
No Drupal site found, only 'drush' cache was cleared.                                                                                                                                                    [warning]

Installing Chado.
Which version of Chado would you like installed?
 [0]  :  Cancel              
 [1]  :  Install Chado v1.3  
 [2]  :  Install Chado v1.2  
 [3]  :  Install Chado v1.11
PHP Fatal error:  Declaration of DatabaseConnection::query($query, array $args = [], $options = []) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs): PDOStatement|false in /home/ron/Public/includes/database/database.inc on line 708
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                       [error]
Error: Declaration of DatabaseConnection::query($query, array $args = [], $options = []) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs):
PDOStatement|false in /home/ron/Public/includes/database/database.inc, line 708
PHP Fatal error:  Declaration of DatabaseConnection::query($query, array $args = [], $options = []) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs): PDOStatement|false in /home/ron/Public/includes/database/database.inc on line 708
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                       [error]
Error: Declaration of DatabaseConnection::query($query, array $args = [], $options = []) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs):
PDOStatement|false in /home/ron/Public/includes/database/database.inc, line 708

Now preparing the site by creating content types.
PHP Fatal error:  Declaration of DatabaseConnection::query($query, array $args = [], $options = []) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs): PDOStatement|false in /home/ron/Public/includes/database/database.inc on line 708
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                       [error]
Error: Declaration of DatabaseConnection::query($query, array $args = [], $options = []) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs):
PDOStatement|false in /home/ron/Public/includes/database/database.inc, line 708
PHP Fatal error:  Declaration of DatabaseConnection::query($query, array $args = [], $options = []) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs): PDOStatement|false in /home/ron/Public/includes/database/database.inc on line 708
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                       [error]
Error: Declaration of DatabaseConnection::query($query, array $args = [], $options = []) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs):
PDOStatement|false in /home/ron/Public/includes/database/database.inc, line 708

Adding permissions for the administrator to view, edit, create, and delete all the newly created content types.
pg_query(): Query failed: ERROR:  relation "tripal_bundle" does not exist                                                                                                                                [warning]
LINE 1: SELECT name FROM tripal_bundle
                         ^ tripal_install.drush.inc:216
An error occurred.
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                       [error]
Error: Return type of HumbugBox3140\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should
be used to temporarily suppress the notice in phar:///usr/local/bin/drush/.box/src/RequirementCollection.php, line 19
```

```

**Comment by dsenalik** [comment]
@alslonik did you ever resolve this? I see the first error is in the drupal install,
`mv: cannot move 'drupal-7.78/includes' to './includes': Directory not empty`
I wonder if that caused all the later problems?

**Comment by dsenalik** [comment]
I'm closing this issue due to lack of activity. Feel free to reopen or to post a new issue if necessary.
