### ISSUE TITLE
Automated tests failing

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1682]
### Tripal Version

4.x

### Drupal Version

10.1.7-dev

### PostgreSQL Version

13.11 (Debian 13.11-0+deb11u1)

### PHP Version

8.2.12

### General Description

Something has started going wrong with automated tests, probably a new version of something is causing things to go awry

### Steps to reproduce

`docker exec --workdir=/var/www/drupal9/web/modules/contrib/tripal container_name phpunit --group 'Tripal Chado Preparer' --debug`

### Error messages

```shell
1) Drupal\Tests\tripal_chado\Functional\Task\ChadoPreparerTest::testChadoPreparer
Drupal\tripal_biodb\Exception\TaskException: Failed to complete schema integration (i.e. Prepare) task.
Undefined array key "name"
Original Exception Trace:
#0 /var/www/drupal/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php(104): PHPUnit\Util\ErrorHandler->__invoke(2, 'Undefined array...', '/var/www/drupal...', 100, Array)
#1 /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Services/ChadoTermsInit.php(100): Symfony\Bridge\PhpUnit\DeprecationErrorHandler::Symfony\Bridge\PhpUnit\{closure}(2, 'Undefined array...', '/var/www/drupal...', 100)
#2 /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Task/ChadoPreparer.php(159): Drupal\tripal_chado\Services\ChadoTermsInit->installTerms()
#3 /var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Task/ChadoPreparerTest.php(45): Drupal\tripal_chado\Task\ChadoPreparer->performTask()
#4 /var/www/drupal/web/sites/simpletest/TestCase.php(1614): Drupal\Tests\tripal_chado\Functional\Task\ChadoPreparerTest->testChadoPreparer()
#5 /var/www/drupal/web/sites/simpletest/TestCase.php(1220): PHPUnit\Framework\TestCase->runTest()
#6 /var/www/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#7 /var/www/drupal/web/sites/simpletest/TestCase.php(970): PHPUnit\Framework\TestResult->run(Object(Drupal\Tests\tripal_chado\Functional\Task\ChadoPreparerTest))
#8 Standard input code(67): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#9 Standard input code(127): __phpunit_run_isolated_test()
#10 {main}

/var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Task/ChadoPreparer.php:201
/var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Task/ChadoPreparerTest.php:45
/var/www/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php:728
```

**Comment by dsenalik** [comment]
I'm a fool. This is why we have tests. Please carry on...
