### ISSUE TITLE
Trying to publish 2+ content types in the same call to the Tripal job launcher fails

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1716]
### Tripal Version

4.x

### Drupal Version

10.1.x-dev

### PostgreSQL Version

13

### PHP Version

8.2

### General Description

**This one is hard to describe generally so look at the steps to reproduce to get a better idea.**

I'm seeing confusing but repeatable errors when publishing content BUT ONLY if I get impatient and submit 2+ publishing jobs before running them.

## Single publish job per call to job launcher works
1. Run tripal jobs to see that the queue is empty.
2. Go to Admin > Tripal > Content > Publish and choose a random content type with unpublished data.
3. Immediately run the tripal job to complete the publishing and then confirm.
4. Repeat above steps exactly and confirm all general content types publish perfectly.

## When multiple publish jobs are in the queue, the second one fails.
**From a fresh install of Tripal or a fresh docker container**
1. Run tripal jobs to see that the queue is empty.
2. Go to Admin > Tripal > Content > Publish and choose a random content type with unpublished data.
3. WITHOUT RUNNING THE JOB LAUNCHER, repeat step 2 for another content type.
4. Now run the tripal jobs and confirm you see a big error and the second content type, regardless of what you chose, failed because it tried to publish data from fields for the first content type.

### Error messages

The following error message was obtained following the steps to reproduce **when multiple publish jobs are in the queue, the second one fails.**

Content types chosen: 1) contact, 2) project.

```
tripal-4x on  4.x via 🐳 desktop-linux via 🐘 v8.1.6 
❯ docker exec -it $containerName drush tripal:trp-run-jobs --username=drupaladmin

2023-12-18 18:21:31
Tripal Job Launcher
Running as user 'drupaladmin'
-------------------
2023-12-18 18:21:31: Job ID 3.
2023-12-18 18:21:31: Calling: tripal_publish(contact, chado_storage, Array)
Step  1 of 6: Find matching records... 
 [notice] Step  1 of 6: Find matching records... 
Step  2 of 6: Generate page titles...
 [notice] Step  2 of 6: Generate page titles...
Step  3 of 6: Find existing published entities...
 [notice] Step  3 of 6: Find existing published entities...
Step  4 of 6: Publishing 7 new entities...
 [notice] Step  4 of 6: Publishing 7 new entities...
Step  5 of 6: Find IDs of entities...
 [notice] Step  5 of 6: Find IDs of entities...
Step  6 of 6: Add field items to published entities...
 [notice] Step  6 of 6: Add field items to published entities...
  Checking for published items for the field: contact_description...
 [notice]   Checking for published items for the field: contact_description...
  Publishing items 7 for field: contact_description...
 [notice]   Publishing items 7 for field: contact_description...
  Checking for published items for the field: contact_name...
 [notice]   Checking for published items for the field: contact_name...
  Publishing items 7 for field: contact_name...
 [notice]   Publishing items 7 for field: contact_name...
  Checking for published items for the field: contact_type...
 [notice]   Checking for published items for the field: contact_type...
  Publishing items 7 for field: contact_type...
 [notice]   Publishing items 7 for field: contact_type...
Published 7 new entities, and 21 field values.
 [notice] Published 7 new entities, and 21 field values.
Done
 [notice] Done
2023-12-18 18:21:32: Job ID 4.
2023-12-18 18:21:32: Calling: tripal_publish(project, chado_storage, Array)
Step  1 of 6: Find matching records... 
 [notice] Step  1 of 6: Find matching records... 
Step  2 of 6: Generate page titles...
 [notice] Step  2 of 6: Generate page titles...
Step  3 of 6: Find existing published entities...
 [notice] Step  3 of 6: Find existing published entities...
Step  4 of 6: Publishing 2 new entities...
 [notice] Step  4 of 6: Publishing 2 new entities...
Step  5 of 6: Find IDs of entities...
 [notice] Step  5 of 6: Find IDs of entities...
Step  6 of 6: Add field items to published entities...
 [notice] Step  6 of 6: Add field items to published entities...
WARNING:   The following fields are not supported by publish at this time: project_analysis, project_contact
 [warning] WARNING:   The following fields are not supported by publish at this time: project_analysis, project_contact
[site http://default] [TRIPAL] WARNING:   The following fields are not supported by publish at this time: project_analysis, project_contact
  Checking for published items for the field: contact_description...
 [notice]   Checking for published items for the field: contact_description...
  Publishing items 2 for field: contact_description...
 [notice]   Publishing items 2 for field: contact_description...
 [warning] Undefined array key "contact_description" TripalPublish.php:702
 [error]  TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in array_keys() (line 702 of /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalPublish.php) #0 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalPublish.php(702): array_keys(NULL)
#1 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalPublish.php(869): Drupal\tripal\Services\TripalPublish->insertFieldItems('contact_descrip...', Array, Array, Array, Array)
#2 /var/www/drupal/web/modules/contrib/tripal/tripal/src/api/tripal.publish.api.php(35): Drupal\tripal\Services\TripalPublish->publish()
#3 [internal function]: tripal_publish('project', 'chado_storage', Array, Object(Drupal\tripal\Services\TripalJob))
#4 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalJob.php(366): call_user_func_array('tripal_publish', Array)
#5 /var/www/drupal/web/modules/contrib/tripal/tripal/src/api/tripal.jobs.api.php(443): Drupal\tripal\Services\TripalJob->run()
#6 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Commands/TripalCommands.php(77): tripal_launch_job(0, '4', -1, 0)
#7 [internal function]: Drupal\tripal\Commands\TripalCommands->runJobs(Array)
#8 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array(Array, Array)
#9 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#10 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(175): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#11 /var/www/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(387): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#12 /var/www/drupal/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/drupal/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/drupal/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/drupal/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/drupal/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run(Array)
#19 /var/www/drupal/vendor/drush/drush/drush(4): require('/var/www/drupal...')
#20 {main}. 
TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalPublish.php on line 702 #0 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalPublish.php(702): array_keys(NULL)
#1 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalPublish.php(869): Drupal\tripal\Services\TripalPublish->insertFieldItems('contact_descrip...', Array, Array, Array, Array)
#2 /var/www/drupal/web/modules/contrib/tripal/tripal/src/api/tripal.publish.api.php(35): Drupal\tripal\Services\TripalPublish->publish()
#3 [internal function]: tripal_publish('project', 'chado_storage', Array, Object(Drupal\tripal\Services\TripalJob))
#4 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalJob.php(366): call_user_func_array('tripal_publish', Array)
#5 /var/www/drupal/web/modules/contrib/tripal/tripal/src/api/tripal.jobs.api.php(443): Drupal\tripal\Services\TripalJob->run()
#6 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Commands/TripalCommands.php(77): tripal_launch_job(0, '4', -1, 0)
#7 [internal function]: Drupal\tripal\Commands\TripalCommands->runJobs(Array)
#8 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array(Array, Array)
#9 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#10 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(175): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#11 /var/www/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(387): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#12 /var/www/drupal/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/drupal/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/drupal/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/drupal/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/drupal/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run(Array)
#19 /var/www/drupal/vendor/drush/drush/drush(4): require('/var/www/drupal...')
#20 {main}
TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in array_keys() (line 702 of /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalPublish.php).
 [warning] Drush command terminated abnormally.
```

**Comment by laceysanderson** [comment]
Working on a non-idealistic kernel test for the publish service to show this issue.
The test is currently creating the entities just fine but is not inserting records into the field tables. According to code coverage it's just stopping in the insertFieldItems() with no error 😕 

```
docker exec --workdir=/var/www/drupal/web/modules/contrib/tripal tripal1716 phpunit --filter testTripalPublishService --coverage-html /var/www/drupal/web/coverage
PHPUnit 9.6.15 by Sebastian Bergmann and contributors.

Testing 
FF                                                                  2 / 2 (100%)

Time: 00:25.415, Memory: 22.00 MB

There were 2 failures:

1) Drupal\Tests\tripal\Kernel\TripalPublishServiceTest::testTripalPublishServiceSingleJob
We expected the number of records in the tripal_entity__organism_genus table to match the number of organisms we inserted.
Failed asserting that actual size 0 matches expected size 3.

/var/www/drupal/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:121
/var/www/drupal/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:55
/var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Kernel/Services/TripalPublishServiceTest.php:112
/var/www/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php:728

2) Drupal\Tests\tripal\Kernel\TripalPublishServiceTest::testTripalPublishService2Jobs
We expected the number of records in the tripal_entity__organism_genus table to match the number of organisms we inserted.
Failed asserting that actual size 0 matches expected size 3.

/var/www/drupal/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:121
/var/www/drupal/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:55
/var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Kernel/Services/TripalPublishServiceTest.php:152
/var/www/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php:728

FAILURES!
Tests: 2, Assertions: 36, Failures: 2.

Generating code coverage report in HTML format ... done [00:08.533]
```

![image](https://github.com/tripal/tripal/assets/1566301/25749a1b-baa9-491b-a4f5-01bd98ea79e4)
