### ISSUE TITLE
Gene entity Display : Issue with Tripal Layout

### ISSUE THREAD

**Issue by SalihaZ** [tripal/tripal#1810]
### Discussion or Question

Hi, I'm new to Drupal 10 and Tripal 4. I've recently tested Tripal Layout for our laboratory project website.

It worked perfectly to display organism and analysis page but I encountered issues to display some of the genes informations. 

In fact, gene entities that are on the first page does not display any information, while for those in the following pages the display works well. 

![Capture d’écran du 2024-03-13 11-45-14](https://github.com/tripal/tripal/assets/72068091/4bf98010-53fa-4338-a934-f170b3e7f0eb)

When I edited the informations of the concerned genes I noticed that the mandatory fields like "organism", “Unique Name“ and “Database Reference Annotations” were not filled. 

![Capture d’écran du 2024-03-13 11-46-11](https://github.com/tripal/tripal/assets/72068091/6cedcd20-1c61-4f42-8157-e1e05cdf972c)

I filled in the missing fields but encountered an error (Exception: Cannot update record in the Chado "feature" table due to unset conditions), and the gene title disappeared.

Here are some screenshots that shows the display after filling the mandatory fields

![Capture d’écran du 2024-03-13 11-26-26](https://github.com/tripal/tripal/assets/72068091/4372e420-beef-48a6-a098-6edf6e9c6da7)
![Capture d’écran du 2024-03-13 12-20-24](https://github.com/tripal/tripal/assets/72068091/dcd71cdc-3da9-450c-9a03-0dd2ba21db62)
![Capture d’écran du 2024-03-13 12-20-53](https://github.com/tripal/tripal/assets/72068091/d0da62dd-2ec7-44d1-ab23-c33f7e2e17c1)

Could you please help me understand where this issue could be coming from and how it's possible to resolve it. 

Thank you in advance for your help.

Saliha

**Comment by dsenalik** [comment]
There could easily be a bug we need to fix.
Can you let us know
 - what version of Tripal you are using, either the alpha 2 release or the current development version?
 - Did you first enter the genes manually or did you load a gff3 file? If you used a gff3 file can you share it?
 - Did you change the theme from the default?
 - What version of Drupal and of PHP are you using?

If we can reproduce the error it will be much easier to find out what is wrong.
On Drupal 10.1 and PHP 8.2 with the alpha2 release of Tripal I was able to manually enter and save a gene.
![palmgene1](https://github.com/tripal/tripal/assets/8419404/5d94e71a-2fdb-4a69-813c-9adee4671c3a)

**Comment by SalihaZ** [comment]
Thanks for your reply.

I'm using Drupal 10 PHP 8 and the latest alpha3 version of Tripal which includes Tripal Layout, and I've followed Stephen's recommendations (https://github.com/tripal/tripal/pull/1792). The fasta and gff3 files have been loaded using the built-in dataloaders, and  Bootstrap 5 theme has been applied.

**Comment by dsenalik** [comment]
Okay, it may be in the loader then. Can you supply a couple of genes from the fasta and gff3 files for us to test? But it may also be in the tripal layout module. For some reason I can't turn that on...
![2024-03-13_tripal_layout_uncheckable](https://github.com/tripal/tripal/assets/8419404/4dc4b3fc-095c-4ae3-943d-bc5c5cb611ba)
Oh it depends on field_group
This is fixed in merged PR #1814

**Comment by dsenalik** [comment]
drupalver = 10.1
phpver    = 8.2
This message has been edited to document how to install the field_group and field_group_table modules
https://www.drupal.org/project/field_group
https://www.drupal.org/project/field_group_table
```
cd /var/www/drupal
composer require 'drupal/field_group:^3.4'
composer require 'drupal/field_group_table:^1.1'
```

**Comment by SalihaZ** [comment]
Here is a sample of gff and fasta I used [sample.zip](https://github.com/tripal/tripal/files/14590429/sample.zip)

I didn't encounter any issues with the installation of the field_group and field_group_table modules. 
![Capture d’écran du 2024-03-13 17-23-06](https://github.com/tripal/tripal/assets/72068091/8ecfd224-36b5-4f6d-b735-4b219357756e)

**Comment by dsenalik** [comment]
My testing procedure
 - first build a new docker on Drupal 10.1 PHP 8.2
 - Create an organism and an analysis
 - Import the test fasta file using "DNA" as the CV term
 - Import the test gff3 file using "DNA" as the CV term
 - Import Genomic content type collection
 - Publish gene content type (76 genes published)
 - View the first gene, it displays as expected.
 -  Edit, and without making changes, save. Error!
 `Cannot update this entity. See the recent logs for more details or contact the site administrator if you cannot view the logs. `
 and the log shows
`PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "featureloc_c1" DETAIL: Key (feature_id, locgroup, rank)=(2, 0, 0) already exists. in /var/www/drupal/web/core/lib/Drupal/Core/Database/StatementWrapperIterator.php:111 Stack trace: #0 /var/www/drupal/web/core/lib/Drupal/Core/Database/StatementWrapperIterator.php(111): PDOStatement->execute(NULL) #1 /var/www/drupal/web/core/modules/pgsql/src/Driver/Database/pgsql/Insert.php(98): Drupal\Core\Database\StatementWrapperIterator->execute(NULL, Array) #2 /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/TripalStorage/ChadoRecords.php(1609): Drupal\pgsql\Driver\Database\pgsql\Insert->execute() #3 /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalStorage/ChadoStorage.php(222): Drupal\tripal_chado\TripalStorage\ChadoRecords->insertRecords('feature', 'featureloc') #4 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Entity/TripalEntity.php(472): Drupal\tripal_chado\Plugin\TripalStorage\ChadoStorage->updateValues(Array) #5 /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(528): Drupal\tripal\Entity\TripalEntity->preSave(Object(Drupal\Core\Entity\Sql\SqlContentEntityStorage)) #6 /var/www/drupal/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(753): Drupal\Core\Entity\EntityStorageBase->doPreSave(Object(Drupal\tripal\Entity\TripalEntity)) #7 /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(483): Drupal\Core\Entity\ContentEntityStorageBase->doPreSave(Object(Drupal\tripal\Entity\TripalEntity)) ...`

This happens because the record was not first deleted by chado storage in `tripal_chado/src/TripalStorage/ChadoRecords.php` function `deleteRecords()`
![2024-03-13_no_pkey_alias_value](https://github.com/tripal/tripal/assets/8419404/c645b7c7-bbf7-47c5-a917-cc19cade2fbb)

This in turn happens because in the load, note that `gene_sequence_coordinates` is not present in the request to `loadValues()`. It _was_ present in validate earlier.
![2024-03-13_no_gene_sequence_coordinates](https://github.com/tripal/tripal/assets/8419404/a01db343-9029-41a6-9dde-97c713b2f20e)

**Update: This has been fixed in core Tripal by merged PR #1861**

**Comment by SalihaZ** [comment]
Thank you very much for your explanations. 

Now I understand the reason why I got the Exception: "Cannot update record in the Chado "feature" table due to unset conditions. Record: Array "
[exception_tripal_lyout.txt](https://github.com/tripal/tripal/files/14600411/exception_tripal_lyout.txt)

I've tested the update and it's now working for the first two genes but it's not working for the remaining genes after filling in the missing fields :(
I got this error:
![Capture d’écran du 2024-03-14 09-31-14](https://github.com/tripal/tripal/assets/72068091/8dca43da-4eb0-4236-a1c8-dd9dfce5f084)

I will soon load others GFFs and FASTAs, I will test if the genes entities informations will be displayed automatically, or if I'll have to manually enter the missing fields.

**Comment by SalihaZ** [comment]
I have another question: I am planning to load other entity types soon. Could Tripal Layout support entities such as mRNA?

**Comment by dsenalik** [comment]
There is a problem, I think in the widget ChadoSequenceCoordinatesWidgetDefault - hopefully I can fix this soon.
I am new to Tripal Layout, but in theory it should support mRNA the same as Gene because they are both based on the chado `feature` table

**Update: This has been fixed in core Tripal by merged PR #1861**

**Comment by dsenalik** [comment]
I want to document some additional problems I am finding
1. ChadoSequenceCoordinatesDefault field should be renamed to ChadoSequenceCoordinatesTypeDefault to follow the naming rules. But to do this an update function would be needed as this breaks an existing site.
2. ChadoSequenceCoordinatesDefault doesn't load all of the values from the `featureloc` table: `rank`, `is_fmax_partial`, `residue_info`, `locgroup`, `rank`
3. Trying to add those reveals that some columns do not have CV terms defined, e.g. `is_fmax_partial`
4. And the ones that do define terms, may be non-existent terms e.g. `local:fmin` does not exist in the CV term table!
5. ChadoSequenceCoordinatesWidgetDefault doesn't pass through the other columns from the `featureloc` table

**Update: This has been fixed in core Tripal by merged PR #1861**

**Comment by dsenalik** [comment]
I have a suggestion for a temporary workaround, just remove the sequence coordinates field from the Gene (or mRNA) content types for now, and see if the other problems persist. This is looking harder to fix than I thought.
You can always add the field back later.

**Comment by SalihaZ** [comment]
OK. You mean these fields ? 
![image](https://github.com/tripal/tripal/assets/72068091/03d9ffb1-0b41-48cd-8586-e23936892364)

![image](https://github.com/tripal/tripal/assets/72068091/57c547ec-3c9d-4187-925b-576e75e049d0)

**Comment by laceysanderson** [comment]
I agree with @dsenalik that it's the coordinate field. You should only need to remove the Sequence coordinate field. This is best done on the manage fields page (admin/structure/bio_data/manage/gene/fields) and clicking the drop down beside the edit to find delete.
<img width="1379" alt="Screenshot 2024-03-14 at 10 34 31 AM" src="https://github.com/tripal/tripal/assets/1566301/815b28b9-7c43-4802-8502-4faa2a76af69">

Tripal Layout does handle all content types and even custom ones, we just haven't made templates for the other content types yet but they should be coming soon! In the meantime you can actually setup the layout using field groups on their own as all Tripal Layout does is automate the process.

**Comment by SalihaZ** [comment]
Thanks @laceysanderson  for your reply.

Actually the field Sequence Coordinates doesn't appear in the Manage fields's page, I didn't have to remove it.
(In the list of existing field neither)

![image](https://github.com/tripal/tripal/assets/72068091/4084f288-d639-402b-894e-135982be88ee)

**Comment by laceysanderson** [comment]
Oooh, interesting. I guess that makes sense as the  coordinates field was added after the most recent release. However, that means that the issue that Doug is seeing and your issue may be different 🙈 

I would update your site to the development version of Tripal, delete the gene content type and then re-import it using the Tripal > Page Structure > Import Content Types and checking "Genomic". That will give you all the most recent field versions for the gene content type without deleting any of your imported data in chado. You may need to delete the genes listed under Tripal > Content first. Again this will not delete anything you imported in chado.

**Comment by dsenalik** [comment]
Notes for the issue of missing terms on chado columns, the following don't have terms defined (I think it may be time to make this a separate issue)
* This is now transferred to issue #1816

**Comment by dsenalik** [comment]
I built a new docker on the 4.x branch just now, imported genomic content field types, and **deleted the sequence coordinates field**.
I am not getting any errors. The first gene as imported:
![20240314_beforeedit](https://github.com/tripal/tripal/assets/8419404/5ca21b98-b3d5-4959-8534-4749986da85c)

Then I edit, and save without changing anything:
![20240314_afteredit](https://github.com/tripal/tripal/assets/8419404/9121090a-6f0f-4802-888b-ab3307c5ad33)

The only difference are some of the linker fields (which are all empty) and the synonym field (also empty) no longer are showing up.

**Comment by SalihaZ** [comment]
Hi,
Thanks @laceysanderson and @dsenalik for your suggestions.

After a git pull on tripal, I have removed the gene content type and re-imported it but I still don't see the sequence_coordinate field. 

The display is worse : Tripal Layout no longer displays any information, and this is the case for all genes (1514 pages) .

![Capture d’écran du 2024-03-19 14-54-55](https://github.com/tripal/tripal/assets/72068091/1291cd3e-4f34-42f4-9fd3-c2036c759c31)

The mandatory fields are emty when I edit a gene

![image](https://github.com/tripal/tripal/assets/72068091/eb69067a-b617-49e9-a554-61c1a601d5bd)

**Comment by dsenalik** [comment]
This is just a guess, but if you didn't already, can you try to re-publish the gene content type?
at `/admin/content/bio_data/publish`

**Comment by SalihaZ** [comment]
I already did it and it didn't change anything :(

**Comment by laceysanderson** [comment]
This is very weird 🤔 I would recommend deleting all the current gene pages, running the updates for your site ([sitename].updates.php) and then republishing the genes. The thing you're seeing with the pages being empty implies the connection between Drupal and Chado for these pages got messed up somehow which I am not able to duplicate on recent versions. 

If you have a large number of genes this can be done using `drush php:cli` and the following code:
```php
// Load all Tripal Content Entities of type gene.
$entities = \Drupal::entityTypeManager()->getStorage('tripal_entity')->loadByProperties(['type' => 'gene']);
// Loop through each one and delete it. This does not delete anything from chado.
foreach ($entities as $entity) {
  $entity->delete();
}
```

Alternative, another option to to start a fresh site which I only mention on the off chance you are in the starting phase of site development where this is not a big deal.

**Comment by SalihaZ** [comment]
I've tried to remove all the gene pages following your suggestion @laceysanderson  but I've got these warnings:

![Capture d’écran du 2024-03-20 12-19-28](https://github.com/tripal/tripal/assets/72068091/7c970982-76e2-4f72-9015-75903f43ac96)

I can't understand the reason. Do you know where this could be coming from?

**Comment by laceysanderson** [comment]
I'm not able to duplicate that at all -both in a site with multiple genes and one with none 🤔 it almost implies there's a serious issue with your site.

What do you get when you run `drush core-status`?

**Comment by pdtouch** [comment]
In my installation, under **Tripal -> Page Structure -> Gene -> Manage Form Display** page, I found Sequence Coordinates was Disabled, I wonder if this is related to this issue.

**Comment by SalihaZ** [comment]
Hi @laceysanderson ,
this is what I get when running `drush core-status`.  It's seem Ok I guess

![Capture d’écran du 2024-03-22 09-54-40](https://github.com/tripal/tripal/assets/72068091/67d91614-02bc-4e2f-91c0-b90c7bd70dea)

**Comment by SalihaZ** [comment]
I've started a fresh site.  Now I can see the sequence coordinate field but the issue is that after I load the fasta and GFF files I coudn't publish them
 
![image](https://github.com/tripal/tripal/assets/72068091/ebe5c867-6ccb-4e77-b6bc-890d5fa3b629)

![image](https://github.com/tripal/tripal/assets/72068091/2062a815-0f36-45b4-88b7-10eb132fc7d0)


the job displays a running status but nothing happened

![image](https://github.com/tripal/tripal/assets/72068091/b090e94f-860e-4d91-851f-df30b48710d3)

**Comment by laceysanderson** [comment]
Hi @SalihaZ it would be worth trying again now with the most recent changes to core. There have been a number of recent PRs merged that would impact and hopefully fix what you were seeing here.

**Comment by SalihaZ** [comment]
Hi @laceysanderson , I took back the first site I started before and I tried to remove the gene pages with the code you provided me using `drush php:cli`. 
It executed without error, however, the pages are deleted in batches. 
I was wondering if this code is supposed to delete everything at once? I have to delete more than 1300 pages !
Thanks in advance !

```
$entities = \Drupal::entityTypeManager()->getStorage('tripal_entity')->loadByProperties(['type' => 'gene']);
foreach ($entities as $entity) {
  $entity->delete();
}
```

**Comment by laceysanderson** [comment]
It is supposed to delete everything at once but maybe the Drupal API has a limit for how many entities it will load to stop timeouts and memory overlow issues 🤔 maybe edit it with a do while loop so it keeps going until there are no more entities to find?

Something like
```php
do {
  $entities = \Drupal::entityTypeManager()->getStorage('tripal_entity')->loadByProperties(['type' => 'gene']);
  foreach ($entities as $entity) {
    $entity->delete();
  }
} while (!empty($entities));
```

**Comment by SalihaZ** [comment]
Hi @laceysanderson, I managed to delete all the pages. However, on this instance, I still cannot publish the genes. 
I also noticed that the sequence coordinates field is missing although I've deleted and re-imported the genomic collection type. 

![Capture d’écran du 2024-05-07 16-15-19](https://github.com/tripal/tripal/assets/72068091/7d2627e8-da2a-411f-b9c1-2dde392b0b95)

Is there a way to modify the database so that I can delete the tripal content types (organism, analysis, genes) without affecting the other contents. Actually, I have made good progress on the design aspect of the site (slideshow etc. ..

**Comment by laceysanderson** [comment]
Are you sure you are on the most recent version of Tripal on this site? 
Specifically, the ideal workflow is:
1. use code above to delete specific content pages that are giving you issues. If an entire content type is giving you issues then delete the content type as well by going to Tripal > Page Structure and choosing delete in the drop down beside that content type. Remember you are deleting both the individual gene pages and also the entire concept of a gene from Tripal before you re-import things.
2. pull most recent changes to tripal core for this site
3. run the updates for the Drupal site if there are any
4. re-import the content types (note: this will only affect the deleted content types, any that are still present will be skipped) confirm that all the fields you expect are now there. if not then confirm that tripal core was actually updated and you may need to delete the content type.
5. since all of the data imported into chado (i.e. records created by the gff3 importer) are still there after deleting the content pages, you do not need to re-import but should just publish at this point)

> Actually, I have made good progress on the design aspect of the site (slideshow etc. ..

This is great to hear!

**Comment by SalihaZ** [comment]
Thanks a lot @laceysanderson for this very detailed response. I followed the steps to the letter but I still don't see the Sequence Coordinates field of the gene type. I tried to add it manually but when I click on continue I got this error.
When I've run the tripal publish, I've only the analysis and the organism displayed but not the genes, may be this is related to the missing sequence coordinates field?

`[Mon May 13 10:13:36.108949 2024] [php:notice] [pid 3179:tid 140441956886272] [client 195.221.174.124:58840] Uncaught PHP Exception Exception: "Cannot create a StorageProperty object for entity type "tripal_entity" field type "chado_sequence_coordinates_default", key "is_fmin_partial" as accession for the property term is not recognized: "local:is_fmin_partial"" at /opt/www/palm-genome-hub.southgreen.fr/web/modules/tripal/tripal/src/TripalStorage/StoragePropertyBase.php line 77, referer: http://dev-palm-genome-hub.southgreen.fr/admin/structure/bio_data/manage/gene/fields/add-field
`
![Capture d’écran du 2024-05-13 09-53-40](https://github.com/tripal/tripal/assets/72068091/d6c65784-a8a3-4342-9404-596c56dbce4b)
![Capture d’écran du 2024-05-13 09-54-07](https://github.com/tripal/tripal/assets/72068091/4a644c64-1a2e-4b2a-a3bd-e52ee87f3f72)
![Capture d’écran du 2024-05-13 09-52-52](https://github.com/tripal/tripal/assets/72068091/d337b9fb-6773-4b79-9dd2-d1787ed2f9b3)

**Comment by dsenalik** [comment]
That missing term was added with the most recent update, specifically 10404

Can you try running
`drush updatedb`
and report if it runs any updates?
If it does, then please try again.

If not, confirm that this update function is in `tripal_chado/tripal_chado.install` line 475 to be sure you are up-to-date.

**Comment by SalihaZ** [comment]
Thanks for your reply @dsenalik .
1) I delete the gene content type 
2) I run the updates
 The update seems to be OK 
![image](https://github.com/tripal/tripal/assets/72068091/65a6ccad-7740-40ef-a7cb-1d7f2d60a6cf)
![Capture d’écran du 2024-05-14 10-00-52](https://github.com/tripal/tripal/assets/72068091/f16ee070-7cc6-402d-8ce3-d790940c0022)
3) I imported again the gene content type; I still don't get the sequence coordinates field and l get the same error when trying to add it.
`Uncaught PHP Exception Exception: "Cannot create a StorageProperty object for entity type  "tripal_entity" field type "chado_sequence_coordinates_default", key "is_fmin_partial" as accession for the property term is not recognized: "local:is_fmin_partial"" at /opt/www/palm-genome-hub.southgreen.fr/web/modules/tripal/tripal/src/TripalStorage/StoragePropertyBase.php line 77, referer: http://dev-palm-genome-hub.southgreen.fr/admin/structure/bio_data/manage/gene/fields/add-field
`

**Comment by laceysanderson** [comment]
Closing as this has become stale. Please start a fresh issue if you are still troubleshooting issues.
