### ISSUE TITLE
oboEbiLookup() probably getting different response causing chado prepare errors

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#2050]
### Tripal Version

4.x

### Drupal Version

any

### PostgreSQL Version

any

### PHP Version

any

### General Description

Automated tests started failing Dec. 3

### Steps to reproduce

Run unit tests with `--filter=testChadoPreparer`
Output is
```
PHPUnit 9.6.21 by Sebastian Bergmann and contributors.

Testing 
Chado Preparer (Drupal\Tests\tripal_chado\Functional\Task\ChadoPreparer)
 ✘ Chado preparer
   │
   │ Drupal\tripal_biodb\Exception\TaskException: Failed to complete schema integration (i.e. Prepare) task.
   │ Undefined array key "is_defining_ontology"
   │ Original Exception Trace:
   │ #0 /var/www/drupal/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php(105): PHPUnit\Util\ErrorHandler->__invoke(2, 'Undefined array...', '/var/www/drupal...', 1364, Array)
   │ #1 /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalImporter/OBOImporter.php(1364): Symfony\Bridge\PhpUnit\DeprecationErrorHandler::Symfony\Bridge\PhpUnit\{closure}(2, 'Undefined array...', '/var/www/drupal...', 1364)
   │ #2 /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalImporter/OBOImporter.php(2110): Drupal\tripal_chado\Plugin\TripalImporter\OBOImporter->findEBITerm('IAO:0000112')
   │ #3 /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalImporter/OBOImporter.php(2409): Drupal\tripal_chado\Plugin\TripalImporter\OBOImporter->cacheTermStanza(Array, 'Typedef')
   │ #4 /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalImporter/OBOImporter.php(1045): Drupal\tripal_chado\Plugin\TripalImporter\OBOImporter->parse('/tmp/obo_wHZuFd', Array)
   │ #5 /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalImporter/OBOImporter.php(1018): Drupal\tripal_chado\Plugin\TripalImporter\OBOImporter->loadOBO_v1_2('/tmp/obo_wHZuFd', 'A vocabulary of...')
   │ #6 /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalImporter/OBOImporter.php(937): Drupal\tripal_chado\Plugin\TripalImporter\OBOImporter->loadOBO_v1_2_url('A vocabulary of...', 'http://purl.obo...', 0)
   │ #7 /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalImporter/OBOImporter.php(881): Drupal\tripal_chado\Plugin\TripalImporter\OBOImporter->loadOBO_v1_2_id(Object(stdClass))
   │ #8 /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Task/ChadoPreparer.php(952): Drupal\tripal_chado\Plugin\TripalImporter\OBOImporter->run()
   │ #9 /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Task/ChadoPreparer.php(160): Drupal\tripal_chado\Task\ChadoPreparer->importOntologies()
   │ #10 /var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Task/ChadoPreparerTest.php(45): Drupal\tripal_chado\Task\ChadoPreparer->performTask()
   │ #11 /var/www/drupal/web/sites/simpletest/TestCase.php(1619): Drupal\Tests\tripal_chado\Functional\Task\ChadoPreparerTest->testChadoPreparer()
   │ #12 /var/www/drupal/web/sites/simpletest/TestCase.php(1225): PHPUnit\Framework\TestCase->runTest()
   │ #13 /var/www/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php(729): PHPUnit\Framework\TestCase->runBare()
   │ #14 /var/www/drupal/web/sites/simpletest/TestCase.php(975): PHPUnit\Framework\TestResult->run(Object(Drupal\Tests\tripal_chado\Functional\Task\ChadoPreparerTest))
   │ #15 Standard input code(67): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
   │ #16 Standard input code(127): __phpunit_run_isolated_test()
   │ #17 {main}
   │
   │ /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Task/ChadoPreparer.php:189
   │ /var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Task/ChadoPreparerTest.php:45
   │ /var/www/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php:729
   │

Time: 03:14.319, Memory: 18.00 MB


ERRORS!
Tests: 1, Assertions: 9, Errors: 1.
```

The url used is
http://www.ebi.ac.uk/ols/api/search?q=IAO:0000112&queryFields=obo_id&local=true

**Comment by dsenalik** [comment]
Apparently `is_defining_ontology` is changed to `isDefiningOntology` but I can't find anything about that with my google searches. A simple few changes allows tests to pass, e.g.
```
-        $defining_ontology = $each['is_defining_ontology'];
+        $defining_ontology = $each['is_defining_ontology'] ?? $each['isDefiningOntology'] ?? 'false';
```
