### ISSUE TITLE
Preparing Chado Fails

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#32]
Hello,

When running the tripal job to prepare chado, I got this error. The error occurred only on the first run. Running the job a second time does not cause the same error and the job completes successfully.

```sh
$drush trp-run-jobs --username=username_here --root=/data/www/html/drupal-7.54
Tripal Job Launcher
Running as user 'username_here'
-------------------
Calling: tripal_chado_prepare_chado(a:0:{}, 1080)

NOTE: Populating of chado_cvterm_mapping table is performed using a database transaction.
If the load fails or is terminated prematurely then the entire set of
insertions/updates is rolled back and will not be found in the database

Examining analysis...
Examining contact...
Examining control...
Examining feature...
Examining featuremap...
Examining genotype...
Examining library...
Examining organism...
Examining phenotype...
Examining phylotree...
Examining project...
Examining protocol...
Examining protocolparam...
Examining pub...
Examining stock...
Examining stockcollection...
Examining studyfactor...
Examining synonym...

Done.
Exception: Exception: SQLSTATE[25P02]: In failed sql transaction: 7  [error]
ERROR:  current transaction is aborted, commands ignored until end of
transaction block: SELECT expire, value FROM {semaphore} WHERE name =
:name; Array
(
[:name] =&gt; field_info:bundle:TripalTerm:TripalTerm
)
in
/data/www/html/drupal-7.54/sites/all/modules/tripal/tripal_chado/includes/tripal_chado.setup.inc:243
Stack trace:
#0
/data/www/html/drupal-7.54/sites/all/modules/tripal/tripal/api/tripal.jobs.api.inc(383):
tripal_chado_prepare_chado('a:0:{}', '1080')
#1
/data/www/html/drupal-7.54/sites/all/modules/tripal/tripal/tripal.drush.inc(173):
tripal_launch_job(0, NULL)
#2 phar:///bin/drush/includes/command.inc(422):
drush_tripal_trp_run_jobs()
#3 phar:///bin/drush/includes/command.inc(231):
_drush_invoke_hooks(Array, Array)
#4 phar:///bin/drush/includes/command.inc(199): drush_command()
#5 phar:///bin/drush/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#6 phar:///bin/drush/includes/preflight.inc(66):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#7 phar:///bin/drush/includes/startup.inc(458): drush_main()
#8 phar:///bin/drush/includes/startup.inc(365): drush_run_main(false,
'/', 'Phar detected. ...')
#9 phar:///bin/drush/drush(114): drush_startup(Array)
#10 /bin/drush(10): require('phar:///bin/dru...')
#11 {main} in
/data/www/html/drupal-7.54/sites/all/modules/tripal/tripal_chado/includes/tripal_chado.setup.inc:332
Stack trace:
#0
/data/www/html/drupal-7.54/sites/all/modules/tripal/tripal/api/tripal.jobs.api.inc(383):
tripal_chado_prepare_chado('a:0:{}', '1080')
#1
/data/www/html/drupal-7.54/sites/all/modules/tripal/tripal/tripal.drush.inc(173):
tripal_launch_job(0, NULL)
#2 phar:///bin/drush/includes/command.inc(422):
drush_tripal_trp_run_jobs()
#3 phar:///bin/drush/includes/command.inc(231):
_drush_invoke_hooks(Array, Array)
#4 phar:///bin/drush/includes/command.inc(199): drush_command()
#5 phar:///bin/drush/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#6 phar:///bin/drush/includes/preflight.inc(66):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#7 phar:///bin/drush/includes/startup.inc(458): drush_main()
#8 phar:///bin/drush/includes/startup.inc(365): drush_run_main(false,
'/', 'Phar detected. ...')
#9 phar:///bin/drush/drush(114): drush_startup(Array)
#10 /bin/drush(10): require('phar:///bin/dru...')
#11 {main}
```

**Comment by spficklin** [comment]
Very strange. I've not seen this error before when installing Tripal v3.   Do you know what steps I could take to reproduce this?

**Comment by almasaeed2010** [comment]
This happened when upgrading our site to Tripal 3. Fortunately, it doesn't occur when in a fresh install. 

The method I used to update our site:
- drush dis tripal_core
- drush pm-update tripal-7.x-3.0-beta3
- drush en tripal_core
- Enabled rest of tripal modules using drupal's interface.
- Prepared chado and got this error.

Sorry for the delayed response!

**Comment by spficklin** [comment]
It may be due to the order that you're enabling modules during the Tripal v2 to Tripal v3 upgrade.   We don't yet have those instructions in the User's Guide, but we do have some in a README.   Try following the instructions here in the section titled "Upgrade from Tripal v2.x to v3.x" and see if that resolves the problem for you.  https://github.com/tripal/tripal/blob/7.x-3.x/README.md
