### ISSUE TITLE
Building Tripal V3.0 from scratch (following the instructions) not working

### ISSUE THREAD

**Issue by igcbioinformatics** [tripal/tripal#534]
I've been trying to follow the Tripal v3.x User's Guide to install a new Tripal instance from scratch, with no success.

I started with an empty Desktop Ubuntu 18.04.1 LTS (also tried with 16.04)

Rapid installation does not work (fails some SQL connector file, even though database and password are correct)

Then I started again from scratch and tried the manual installation but that does not work either.
In this case, it fails when I try to install tripal with drush.

When I try "drush pm-enable tripal", it says it is not downloaded (which it is), it asks to download, which even if I do (ovewriting the previous one), it still says it is not downloaded and refuses to install.

Any hints welcome...

I've done this already a few years ago (Tripal V2.0) and I was able to install just fine

Thanks,
Daniel

**Comment by btski** [comment]
Sounds like you might have a problem with a config file for the rapid install. When building from scratch, are you running "drush pm-enable tripal" from the correct directory (/var/www/html)?

I've posted my own personal notes for rapid install (found [here](https://github.com/tripal/tripal/issues/175)). Perhaps comparing what you've tried might be able to help solve your problem/s.

Please confirm that you do not see the following error prompt:

```
WD php: Exception: Resolve all issues below to continue the          [error]
installation. For help configuring your database server, see the
installation handbook, or contact your hosting provider.Failed to
connect to your database server. The server reports the following
message: SQLSTATE[08006] [7] FATAL:  password authentication failed
for user &quot;username&quot;
```

**Comment by laceysanderson** [comment]
Can you paste the full transcript from the terminal for us? Note: use ``` above and below to make it more readable :-)

**Comment by btski** [comment]
Actually there does appear to be a problem (at least with rapid install). Installing Tripal is failing post Chado version (1.3) selection and resulting in the following errors:

```
PHP Fatal error:  Uncaught Error: Call to undefined function cache_get() in /var/www/html/includes/module.inc:754
Stack trace:
#0 /var/www/html/includes/module.inc(954): module_implements('system_theme_in...')
#1 /var/www/html/modules/system/system.module(2511): module_invoke_all('system_theme_in...')
#2 /var/www/html/includes/theme.inc(798): _system_rebuild_theme_data()
#3 /var/www/html/includes/theme.maintenance.inc(57): list_themes()
#4 /var/www/html/includes/bootstrap.inc(2881): _drupal_maintenance_theme()
#5 /var/www/html/includes/errors.inc(179): drupal_maintenance_theme()
#6 /var/www/html/includes/bootstrap.inc(2609): _drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /var/www/html/includes/module.inc on line 754
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Uncaught Error: Call to undefined function cache_get() in
/var/www/html/includes/module.inc:754
Stack trace:
#0 /var/www/html/includes/module.inc(954):
module_implements('system_theme_in...')
#1 /var/www/html/modules/system/system.module(2511):
module_invoke_all('system_theme_in...')
#2 /var/www/html/includes/theme.inc(798):
_system_rebuild_theme_data()
#3 /var/www/html/includes/theme.maintenance.inc(57): list_themes()
#4 /var/www/html/includes/bootstrap.inc(2881):
_drupal_maintenance_theme()
#5 /var/www/html/includes/errors.inc(179): drupal_maintenance_theme()
#6 /var/www/html/includes/bootstrap.inc(2609):
_drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /var/www/html/includes/module.inc, line 754
The external command could not be executed due to an application     [error]
error.
PHP Fatal error:  Uncaught Error: Call to undefined function cache_get() in /var/www/html/includes/module.inc:754
Stack trace:
#0 /var/www/html/includes/module.inc(954): module_implements('system_theme_in...')
#1 /var/www/html/modules/system/system.module(2511): module_invoke_all('system_theme_in...')
#2 /var/www/html/includes/theme.inc(798): _system_rebuild_theme_data()
#3 /var/www/html/includes/theme.maintenance.inc(57): list_themes()
#4 /var/www/html/includes/bootstrap.inc(2881): _drupal_maintenance_theme()
#5 /var/www/html/includes/errors.inc(179): drupal_maintenance_theme()
#6 /var/www/html/includes/bootstrap.inc(2609): _drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /var/www/html/includes/module.inc on line 754
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Uncaught Error: Call to undefined function cache_get() in
/var/www/html/includes/module.inc:754
Stack trace:
#0 /var/www/html/includes/module.inc(954):
module_implements('system_theme_in...')
#1 /var/www/html/modules/system/system.module(2511):
module_invoke_all('system_theme_in...')
#2 /var/www/html/includes/theme.inc(798):
_system_rebuild_theme_data()
#3 /var/www/html/includes/theme.maintenance.inc(57): list_themes()
#4 /var/www/html/includes/bootstrap.inc(2881):
_drupal_maintenance_theme()
#5 /var/www/html/includes/errors.inc(179): drupal_maintenance_theme()
#6 /var/www/html/includes/bootstrap.inc(2609):
_drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /var/www/html/includes/module.inc, line 754
The external command could not be executed due to an application     [error]
error.

Now preparing the site by creating content types.
PHP Fatal error:  Uncaught Error: Call to undefined function cache_get() in /var/www/html/includes/module.inc:754
Stack trace:
#0 /var/www/html/includes/module.inc(954): module_implements('system_theme_in...')
#1 /var/www/html/modules/system/system.module(2511): module_invoke_all('system_theme_in...')
#2 /var/www/html/includes/theme.inc(798): _system_rebuild_theme_data()
#3 /var/www/html/includes/theme.maintenance.inc(57): list_themes()
#4 /var/www/html/includes/bootstrap.inc(2881): _drupal_maintenance_theme()
#5 /var/www/html/includes/errors.inc(179): drupal_maintenance_theme()
#6 /var/www/html/includes/bootstrap.inc(2609): _drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /var/www/html/includes/module.inc on line 754
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Uncaught Error: Call to undefined function cache_get() in
/var/www/html/includes/module.inc:754
Stack trace:
#0 /var/www/html/includes/module.inc(954):
module_implements('system_theme_in...')
#1 /var/www/html/modules/system/system.module(2511):
module_invoke_all('system_theme_in...')
#2 /var/www/html/includes/theme.inc(798):
_system_rebuild_theme_data()
#3 /var/www/html/includes/theme.maintenance.inc(57): list_themes()
#4 /var/www/html/includes/bootstrap.inc(2881):
_drupal_maintenance_theme()
#5 /var/www/html/includes/errors.inc(179): drupal_maintenance_theme()
#6 /var/www/html/includes/bootstrap.inc(2609):
_drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /var/www/html/includes/module.inc, line 754
The external command could not be executed due to an application     [error]
error.
PHP Fatal error:  Uncaught Error: Call to undefined function cache_get() in /var/www/html/includes/module.inc:754
Stack trace:
#0 /var/www/html/includes/module.inc(954): module_implements('system_theme_in...')
#1 /var/www/html/modules/system/system.module(2511): module_invoke_all('system_theme_in...')
#2 /var/www/html/includes/theme.inc(798): _system_rebuild_theme_data()
#3 /var/www/html/includes/theme.maintenance.inc(57): list_themes()
#4 /var/www/html/includes/bootstrap.inc(2881): _drupal_maintenance_theme()
#5 /var/www/html/includes/errors.inc(179): drupal_maintenance_theme()
#6 /var/www/html/includes/bootstrap.inc(2609): _drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /var/www/html/includes/module.inc on line 754
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Uncaught Error: Call to undefined function cache_get() in
/var/www/html/includes/module.inc:754
Stack trace:
#0 /var/www/html/includes/module.inc(954):
module_implements('system_theme_in...')
#1 /var/www/html/modules/system/system.module(2511):
module_invoke_all('system_theme_in...')
#2 /var/www/html/includes/theme.inc(798):
_system_rebuild_theme_data()
#3 /var/www/html/includes/theme.maintenance.inc(57): list_themes()
#4 /var/www/html/includes/bootstrap.inc(2881):
_drupal_maintenance_theme()
#5 /var/www/html/includes/errors.inc(179): drupal_maintenance_theme()
#6 /var/www/html/includes/bootstrap.inc(2609):
_drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /var/www/html/includes/module.inc, line 754
The external command could not be executed due to an application     [error]
error.

Adding permissions for the administrator to view, edit, create, and delete all the newly created content types.
pg_pconnect(): Unable to connect to PostgreSQL server: FATAL:        [warning]
password authentication failed for user "drupal"
FATAL:  password authentication failed for user "drupal"
tripal_install.drush.inc:211
An error occurred when attempting to perimssion the administrator. Please navigate to your new site and add permissions to your new content types here admin/people/permissions.
Drush command terminated abnormally due to an unrecoverable error.   [error]
```

It seems the github repository was modified ~2 months ago. The last time I ran a full installation was at least 4 months ago.

**Comment by igcbioinformatics** [comment]
Hello:

```
- Downloaded ubuntu-18.04.1-desktop-amd64.iso from ubuntu
- Made a new VM (using KVM) 4GB RAM, 30GB disk, 2CPU
- installed ubuntu from the ISO

Did an update:
> 'sudo apt-get update; sudo apt-get upgrade'
Installed openssh to be able to connect:
> 'sudo apt-get install openssh-server'

Then followed this http://tripal.info/tutorials/v3.x/installation/server-setup/ubuntu-18.04:
> 'sudo apt-get install apache2'
> 'cd /etc/apache2/mods-enabled'
> 'sudo ln -s ../mods-available/rewrite.load'
> 'sudo pico /etc/apache2/sites-available/000-default.conf'
Added this bit in the file in the specified location:
'
   <Directory /var/www/html>
      Options Indexes FollowSymLinks MultiViews
      AllowOverride All
      Order allow,deny
      allow from all
   </Directory>
'
> 'sudo service apache2 restart'
> 'sudo apt-get install php php-dev php-cli libapache2-mod-php'
> 'sudo apt-get install php-pgsql php-gd php-xml'
> 'sudo pico /etc/php/7.2/apache2/php.ini'
Changed to 'memory_limit = 2048M'
> 'sudo service apache2 restart'
> 'sudo apt-get install postgresql'
> 'sudo apt-get install phppgadmin'

Next, I installed drush following what is here https://www.drupal.org/node/1248790:
> ' sudo apt install curl'
> 'cd ~'
> 'curl -sS https://getcomposer.org/installer | php'
> 'sudo mv composer.phar /usr/local/bin/composer'
> 'composer global require drush/drush:7.*'
> 'export PATH="$HOME/.config/composer/vendor/bin:$PATH"'

When checking drush, I get this warning:
> 'drush --version'
count(): Parameter must be an array or an object that implements Countable Table.php:789                                         [warning]
 Drush Version   :  7.4.0
(NB: should I install a different version of drush?)

Next, I follow the rapid installation http://tripal.info/tutorials/v3.x/installation/rapid:
> 'sudo su - postgres'
> 'createuser -P drupal' 
> 'createdb drupal -O drupal'
> 'exit'
> 'cd /var/www/html'
> 'sudo chown -R [install_user] /var/www/html'
> 'sudo apt install git'
> 'git clone https://github.com/tripal/tripal_install.git'
> 'mv tripal_install/* ./'
> 'drush --include=. tripal-generic-install'
Name of the site: [mysitename]
Admin email for the site: [myemail]
Name for your admin user on the site: admin
Password for admin: [adminpass]
database name: drupal
postgres username: drupal
postgres password: [same as used on createuser]
host: 127.0.0.1
port: 5432

It fails, but now I have a different error from yesterday:

"
The following extensions will be enabled: tripal, tripal_chado, tripal_ds, tripal_ws, php, tripal_chado_views
Do you really want to continue? (y/n): y
PHP Fatal error:  Declaration of TripalVocabController::delete($entity) must be compatible with EntityAPIController::delete($ids, ?DatabaseTransaction $transaction = NULL) in /var/www/html/sites/all/modules/tripal/tripal/includes/TripalVocabController.inc on line 8
Drush command terminated abnormally due to an unrecoverable error.                                                               [error]
Error: Declaration of TripalVocabController::delete($entity) must be compatible with EntityAPIController::delete($ids,
?DatabaseTransaction $transaction = NULL) in /var/www/html/sites/all/modules/tripal/tripal/includes/TripalVocabController.inc,
line 8
The external command could not be executed due to an application error.                                                          [error]
"

```

**Comment by igcbioinformatics** [comment]
Another attempt:
Did exactly the same as before, but now tried the manual installation

```
Next, I follow this http://tripal.info/tutorials/v3.x/installation/manual:
> 'sudo su - postgres'
> 'createuser -P drupal'
> 'createdb drupal -O drupal'
> 'exit'
> 'sudo chown -R [user] /var/www/html'
> 'cd /var/www/html'
> 'wget http://ftp.drupal.org/files/projects/drupal-7.59.tar.gz'
> 'tar -zxvf drupal-7.59.tar.gz'
> 'mv drupal-7.59/* ./'
> 'mv drupal-7.59/.htaccess ./'
> 'mv index.html index.html.orig'
> ' ls -l .htaccess'
> ' cd /var/www/html/sites/default/'
> 'cp default.settings.php settings.php'
> 'pico settings.php'
MAde sure this info is in there: 
$databases = array();
$databases['default']['default'] = array(
  'driver' => 'pgsql',
  'database' => 'drupal',
  'username' => 'drupal',
  'password' => 'password - yes, the right password',
  'host' => 'localhost',
  'prefix' => '',
);

The went to http://localhost/install.php
Had a warning on a recommended Unicode library but otherwise went fine.
Then I have a few php warnings... 
Eg. 'Deprecated function: The each() function is deprecated.'
Eg. Warning: count(): Parameter must be an array or an object that implements Countable ...'
But otherwise the drupal site seems to work

> 'cd /var/www/html/sites/all/modules'
> 'drush pm-download entity'
> 'drush pm-enable entity'
> 'drush pm-download views ctools drush pm-download ds field_group field_group_table field_formatter_class field_formatter_settings'
> 'drush pm-enable ds field_group field_group_table field_formatter_class field_formatter_settings'
> 'drush pm-download ckeditor'
> 'drush pm-enable ckeditor'
All goes fine

> 'drush pm-download tripal'
Seems ok
> 'cd /var/www/html'
> 'wget --no-check-certificate https://drupal.org/files/drupal.pgsql-bytea.27.patch'
> 'patch -p1 < drupal.pgsql-bytea.27.patch'

> 'cd /var/www/html/sites/all/modules/views'
> 'patch -p1 < ../tripal/tripal_chado_views/views-sql-compliant-three-tier-naming-1971160-30.patch'
This does not work... only tripal_views folder exists, and the patch does not work anyway...

> 'drush pm-enable tripal'
"
tripal was not found.                                                                                                                       [warning]
The following projects provide some or all of the extensions not found:                                                                     
Would you like to download them? (y/n):
"
If I say 'y' it says it is already downloaded, but does not work anyway...

```

**Comment by igcbioinformatics** [comment]
I've tried the automatic process with 16.04 and seems to be working now.

**Comment by almasaeed2010** [comment]
Hello @igcbioinformatics 

For the time being, Drupal does not support PHP 7.2. When using Ubuntu 18, it auto installs php 7.2 and that's why your earlier attempts failed. 

@laceysanderson @spficklin should we add a warning on the site that PHP 7.2 is not fully supported?

Thanks!

**Comment by spficklin** [comment]
I am able to run Tripal v3 with Ubuntu 18.04 without a problem.   However, @almasaeed2010 is correct, PHP 7.2 that comes with Ubu 18.04 does not get along with Drupal and it causes warning messages. Perhaps we've accidentally incorporated a change in the code that breaks the install on 18.04.  But, I've certainly done it in the past.  I'll look into it.

**Comment by dsobral** [comment]
I noticed the warnings, and I figured it was something with the php version.

Thanks,
Daniel

**Comment by almasaeed2010** [comment]
For the record, I managed to install tripal manually on Ubuntu 18 (php 7.2) without any issues.

I tried the rapid install method but it is downloading an old version of tripal 7.x-3.0-rc1 which has an issue when I tried to enable it:

```
PHP Fatal error:  Declaration of TripalVocabController::delete($entity) must be compatible with EntityAPIController::delete($ids, ?DatabaseTransaction $transaction = NULL) in /var/www/html/sites/all/modules/tripal/tripal/includes/TripalVocabController.inc on line 8
```

Other than that everything worked well!

Thanks!

**Comment by spficklin** [comment]
Thanks for testing @almasaeed2010 . I have updated the rapid install script to use 7.x-3.x-rc3 release. And that message you report should be resolved in the rc3 version.

@igcbioinformatics if you want to try the 18.04 again and let us know if you have issues with it we can try to help.  If you're happy with your 16.04 installation then let me know and I'll close out the issue.

**Comment by igcbioinformatics** [comment]
I tried again with 18.04, and when I gave a complex password (with, for example the character '#') I had an error : 

```
2018-08-14 17:24:46 (12,1 MB/s) - ‘drupal-7.59.tar.gz’ saved [3282260/3282260]

Drush\Sql\SqlException: Unable to find a matching SQL Class. Drush cannot find your database connection details. in     [error]
/home/ubi/.config/composer/vendor/drush/drush/commands/sql/sql.drush.inc:597
Stack trace:
#0 /home/ubi/.config/composer/vendor/drush/drush/commands/sql/sql.drush.inc(582): drush_sql_get_class(Array)
#1 /home/ubi/.config/composer/vendor/drush/drush/commands/core/site_install.drush.inc(109): drush_sql_get_class()
#2 /home/ubi/.config/composer/vendor/drush/drush/includes/command.inc(361): drush_core_pre_site_install('standard',
'install_configu...')
#3 /home/ubi/.config/composer/vendor/drush/drush/includes/command.inc(212): _drush_invoke_hooks(Array, Array)
#4 /home/ubi/.config/composer/vendor/drush/drush/includes/command.inc(180): drush_command('standard',
'install_configu...')
#5 /home/ubi/.config/composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(64): drush_dispatch(Array)
#6 /home/ubi/.config/composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#7 /home/ubi/.config/composer/vendor/drush/drush/drush.php(11): drush_main()
#8 {main}

```

I then run again, changing the password to something simple, and now it seems to work.
So this might explain part of the issues I was observing.

Daniel

**Comment by bradfordcondon** [comment]
hi @igcbioinformatics 

Drupal uses `parse_url()`(http://php.net/manual/en/function.parse-url.php) to handle the database connection.  This means that `/ . @ # , ` all break the connection, and they shouldnt be used.

**Comment by igcbioinformatics** [comment]
Yes, didn't think about it when automatically generating the password...
But before, 18.04 was still breaking (though 16.04 worked)

Now both work.

Thanks,
Daniel

**Comment by spficklin** [comment]
@igcbioinformatics just to follow-up.  Where did you provide the password with the '#' character that caused problems?

**Comment by igcbioinformatics** [comment]
I've provided the password during the steps after "drush --include=. tripal-generic-install"

Daniel

**Comment by spficklin** [comment]
Okay Thanks for sharing your experience.  I've added a new issue so we can fix this for the future:  https://github.com/tripal/tripal_install/issues/5
