### ISSUE TITLE
Crash when using drupal pm-enable for multiple modules

### ISSUE THREAD

**Issue by mboudet** [tripal/tripal#858]
### System information

System info:
Tripal: 7.x-3.0
Drupal : 7.59
Postgres: 9.5.8
Php: 7.1.23

### Issue description
Hello.

We decided to update our Tripal version on the docker-tripal repo.
Starting from [this commit](https://github.com/tripal/tripal/commit/8474410e47e71d170545432e8046e9ae27981cf2), we started seeing crashes during the install phase.

Namely, we have a step where we install all modules with a `drupal pm-enable $module_list`
Up until this commit, this worked fine.

#### Steps to reproduce

Run this after install (and downloading the modules)

`drush pm enable tripal_analysis_blast tripal_analysis_interpro tripal_analysis_go tripal_rest_api tripal_elasticsearch tripal_analysis_expression`

It should crash with a field error.

```
tripal_1         | The following extensions will be enabled: tripal_analysis_blast, tripal_analysis_interpro, tripal_analysis_go, tripal_rest_api, tripal_elasticsearch, tripal_analysis_expression,  queue_ui, jquery_update, tripal_biomaterial
tripal_1         | Do you really want to continue? (y/n): y
tripal_1         | INFO (TRIPAL_ENTITIES): Done.
tripal_1         | WD tripal_entities: Done.                                                 [info]
tripal_1         | WD system: jquery_update module installed.                                [info]
tripal_1         | WD system: jquery_update module enabled.                                  [info]
tripal_1         | WD system: queue_ui module installed.                                     [info]
tripal_1         | WD system: queue_ui module enabled.                                       [info]
tripal_1         | Done.
tripal_1         | INFO (TRIPAL_ENTITIES): Done.
tripal_1         | WD tripal_entities: Done.                                                 [info]
tripal_1         | WD system: tripal_analysis_blast module installed.                        [info]
tripal_1         | WD system: tripal_analysis_blast module enabled.                          [info]
tripal_1         | WD system: tripal_biomaterial module installed.                           [info]
tripal_1         | WD system: tripal_biomaterial module enabled.                             [info]
tripal_1         | WD system: tripal_analysis_expression module installed.                   [info]
tripal_1         | WD system: tripal_analysis_expression module enabled.                     [info]
tripal_1         | WD system: tripal_analysis_go module installed.                           [info]
tripal_1         | WD system: tripal_analysis_go module enabled.                             [info]
tripal_1         | WD tripal_entities: Failed to create content type: Attempt to create     [error]
tripal_1         | a field of unknown type data__gene_expression_data..
tripal_1         | [21-Feb-2019 09:02:49 UTC] [site http://default] [TRIPAL ERROR] [TRIPAL_ENTITIES] Failed to create content type: Attempt to create a field of unknown type <em class="placeholder">data__gene_expression_data</em>..
tripal_1         | ERROR (TRIPAL_ENTITIES): Failed to create content type: Attempt to create a field of unknown type <em class="placeholder">data__gene_expression_data</em>..
tripal_1         | Exception: Error encountered creating InterPro results Content Type.     [error]
tripal_1         | in
tripal_1         | /var/www/html/sites/all/modules/tripal_analysis_interpro/tripal_analysis_interpro.install:286
tripal_1         | Stack trace:
tripal_1         | #0
tripal_1         | /var/www/html/sites/all/modules/tripal_analysis_interpro/tripal_analysis_interpro.install(24):
tripal_1         | tripal_analysis_interpro_create_entity_type()
tripal_1         | #1 /var/www/html/includes/module.inc(934):
tripal_1         | tripal_analysis_interpro_install()
tripal_1         | #2 /var/www/html/includes/module.inc(498):
tripal_1         | module_invoke('tripal_analysis...', 'install')
tripal_1         | #3
tripal_1         | /root/.composer/vendor/drush/drush/commands/core/drupal/environment_7.inc(143):
tripal_1         | module_enable(Array)
tripal_1         | #4 /root/.composer/vendor/drush/drush/commands/pm/pm.drush.inc(1122):
tripal_1         | drush_module_enable(Array)
tripal_1         | #5 /root/.composer/vendor/drush/drush/includes/command.inc(361):
tripal_1         | drush_pm_enable('tripal_analysis...', 'tripal_analysis...',
tripal_1         | 'tripal_analysis...', 'tripal_rest_api', 'tripal_elastics...',
tripal_1         | 'tripal_analysis...', 'tripal_bipaa_ui')
tripal_1         | #6 /root/.composer/vendor/drush/drush/includes/command.inc(212):
tripal_1         | _drush_invoke_hooks(Array, Array)
tripal_1         | #7 /root/.composer/vendor/drush/drush/includes/command.inc(180):
tripal_1         | drush_command('tripal_analysis...', 'tripal_analysis...',
tripal_1         | 'tripal_analysis...', 'tripal_rest_api', 'tripal_elastics...',
tripal_1         | 'tripal_analysis...', 'tripal_bipaa_ui')
tripal_1         | #8
tripal_1         | /root/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(64):
tripal_1         | drush_dispatch(Array)
tripal_1         | #9 /root/.composer/vendor/drush/drush/drush.php(70):
tripal_1         | Drush\Boot\BaseBoot->bootstrap_and_dispatch()
tripal_1         | #10 /root/.composer/vendor/drush/drush/drush.php(11): drush_main()
tripal_1         | #11 {main}
tripal_1         | Command dispatch complete                                               [notice]
rhynchophorus_ferrugineus_tripal_1 exited with code 1
```

Seems like it tries to create an entity type using other modules fields, but they are not properly set up yet, so it crash..

#### Notes

Since the changes are cache-related, the issue might be on my end (with other various caches issues in the docker)
We fixed it by using a `drush pm-enable` loop for each module, instead of all modules at the same time, so this bug is not an emergency by any mean.

**Comment by bradfordcondon** [comment]
looks like the expression module's field isnt available when creating the interpro entity. 

I can reproduce this problem on my own site (apache, postgres running natively on OSX)

```

Directory /Users/bc/.drush/cache/default exists, but is not writable. Please check directory           [error]
permissions.
The following extensions will be enabled: tripal_analysis_blast, tripal_analysis_interpro, tripal_analysis_go, tripal_analysis_expression, jquery_update, tripal_biomaterial
Do you really want to continue? (y/n): y
Done.
INFO (TRIPAL_ENTITIES): Done.
WD tripal_entities: Failed to create content type: Attempt to create a field of unknown type           [error]
data__gene_expression_data..
ERROR (TRIPAL_ENTITIES): Failed to create content type: Attempt to create a field of unknown type <em class="placeholder">data__gene_expression_data</em>..
[site http://default] [TRIPAL ERROR] [TRIPAL_ENTITIES] Failed to create content type: Attempt to create a field of unknown type <em class="placeholder">data__gene_expression_data</em>..
Exception: Error encountered creating InterPro results Content Type. in                                [error]
/Users/bc/tripal/sites/all/modules/custom/tripal_analysis_interpro/tripal_analysis_interpro.install:286
Stack trace:
#0
/Users/bc/tripal/sites/all/modules/custom/tripal_analysis_interpro/tripal_analysis_interpro.install(24):
tripal_analysis_interpro_create_entity_type()
#1 /Users/bc/tripal/includes/module.inc(934): tripal_analysis_interpro_install()
#2 /Users/bc/tripal/includes/module.inc(498): module_invoke('tripal_analysis...', 'install')
#3 /Users/bc/.composer/vendor/drush/drush/commands/core/drupal/environment_7.inc(143):
module_enable(Array)
#4 /Users/bc/.composer/vendor/drush/drush/commands/pm/pm.drush.inc(1122): drush_module_enable(Array)
#5 /Users/bc/.composer/vendor/drush/drush/includes/command.inc(361):
drush_pm_enable('tripal_analysis...', 'tripal_analysis...', 'tripal_analysis...', 'tripal_analysis...')
#6 /Users/bc/.composer/vendor/drush/drush/includes/command.inc(212): _drush_invoke_hooks(Array, Array)
#7 /Users/bc/.composer/vendor/drush/drush/includes/command.inc(180):
drush_command('tripal_analysis...', 'tripal_analysis...', 'tripal_analysis...', 'tripal_analysis...')
#8 /Users/bc/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(64): drush_dispatch(Array)
#9 /Users/bc/.composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#10 /Users/bc/.composer/vendor/drush/drush/drush.php(11): drush_main()
#11 {main}
___________________________________________________________
```

I'm in agreement that the problem can be sidestepped easily (enable one by one instead). I'm thinking the solution is to trigger the entity/field connection at the end of each module enabling or something like that?

**Comment by spficklin** [comment]
Hi Folks, just checking if anything needs to be done for this.

**Comment by mboudet** [comment]
Well in our case, we sidestepped the issue by looping on the drush enable.
If no changes are made, it might be good to add a warning about the issue in the docs.

**Comment by spficklin** [comment]
@abretaud do you have any thoughts on this as it involves the Docker images?

**Comment by abretaud** [comment]
Well, it seems like it's not specific to docker images as @bradfordcondon reproduced it outside docker.
It would be great to either warn people that enabling several modules at one can fail, or find a way to avoid the error.
As @mboudet I'm happy with enabling one by one until then

**Comment by spficklin** [comment]
Thanks @abretaud .  I should have read this more closely. As these are all extension modules, i'm not sure we can do anything about it in the core Tripal package.  

If the problem is that the Tripal Analysis Expression module can not create the field for the term `data:gene_expression_data` then I would suspect there's a dependency that isn't being met properly in the module?  You should be able to install the modules in a list and Drush is supposed to work out the dependencies as long as they are defined.

**Comment by mboudet** [comment]
As far as I recall, the issue is not related to the Analysis_expression module in itself.
If I use another set of modules, (or just don't install this one), it will crash on another module with another field error.

It's been a while, but I think the issue was that tripal starts enabling other modules without waiting for them to be properly set up..

I'm not exactly sure how the commit broke this however.

**Comment by spficklin** [comment]
Okay, thanks for the clarification... we'll have to test further to see what went wrong.

**Comment by bradfordcondon** [comment]
yep if i recall, it isn't a dependency issue.  Whats going on is a field from module X will try to attach to a bundle defined in module Y.  Im not sure which isnt ready- the field or hte bundle.

To reproduce cleanly, define a custom anaysis bundle in one module, and a field that attaches to any analysis bundles in another, and enable them at once.  It shouldnt be module specific (IE a problem with analysis expression or intero).

**Comment by laceysanderson** [comment]
This can be solved by enabling each module separately. We should add mention of this in the docs in warning form.

Additionally I'm going to add the tag to ensure this is not a problem in Tripal 4
